package lk.geoedge.interoperability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CanlendarCropSeasonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanlendarCropSeasonAllPropertiesEquals(CanlendarCropSeason expected, CanlendarCropSeason actual) {
        assertCanlendarCropSeasonAutoGeneratedPropertiesEquals(expected, actual);
        assertCanlendarCropSeasonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanlendarCropSeasonAllUpdatablePropertiesEquals(CanlendarCropSeason expected, CanlendarCropSeason actual) {
        assertCanlendarCropSeasonUpdatableFieldsEquals(expected, actual);
        assertCanlendarCropSeasonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanlendarCropSeasonAutoGeneratedPropertiesEquals(CanlendarCropSeason expected, CanlendarCropSeason actual) {
        assertThat(actual)
            .as("Verify CanlendarCropSeason auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanlendarCropSeasonUpdatableFieldsEquals(CanlendarCropSeason expected, CanlendarCropSeason actual) {
        assertThat(actual)
            .as("Verify CanlendarCropSeason relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPeriod()).as("check period").isEqualTo(expected.getPeriod()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanlendarCropSeasonUpdatableRelationshipsEquals(CanlendarCropSeason expected, CanlendarCropSeason actual) {
        // empty method
    }
}
