package lk.geoedge.interoperability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CropVarietyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropVarietyAllPropertiesEquals(CropVariety expected, CropVariety actual) {
        assertCropVarietyAutoGeneratedPropertiesEquals(expected, actual);
        assertCropVarietyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropVarietyAllUpdatablePropertiesEquals(CropVariety expected, CropVariety actual) {
        assertCropVarietyUpdatableFieldsEquals(expected, actual);
        assertCropVarietyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropVarietyAutoGeneratedPropertiesEquals(CropVariety expected, CropVariety actual) {
        assertThat(actual)
            .as("Verify CropVariety auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropVarietyUpdatableFieldsEquals(CropVariety expected, CropVariety actual) {
        assertThat(actual)
            .as("Verify CropVariety relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getNoOfStages()).as("check noOfStages").isEqualTo(expected.getNoOfStages()))
            .satisfies(a -> assertThat(a.getImage()).as("check image").isEqualTo(expected.getImage()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getAddedBy()).as("check addedBy").isEqualTo(expected.getAddedBy()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCropVarietyUpdatableRelationshipsEquals(CropVariety expected, CropVariety actual) {
        assertThat(actual)
            .as("Verify CropVariety relationships")
            .satisfies(a -> assertThat(a.getCrop()).as("check crop").isEqualTo(expected.getCrop()))
            .satisfies(a -> assertThat(a.getCropDuration()).as("check cropDuration").isEqualTo(expected.getCropDuration()));
    }
}
