package lk.geoedge.interoperability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CultivatedLandDamageReasonDamageTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReasonDamageTypeAllPropertiesEquals(
        CultivatedLandDamageReasonDamageType expected,
        CultivatedLandDamageReasonDamageType actual
    ) {
        assertCultivatedLandDamageReasonDamageTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertCultivatedLandDamageReasonDamageTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReasonDamageTypeAllUpdatablePropertiesEquals(
        CultivatedLandDamageReasonDamageType expected,
        CultivatedLandDamageReasonDamageType actual
    ) {
        assertCultivatedLandDamageReasonDamageTypeUpdatableFieldsEquals(expected, actual);
        assertCultivatedLandDamageReasonDamageTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReasonDamageTypeAutoGeneratedPropertiesEquals(
        CultivatedLandDamageReasonDamageType expected,
        CultivatedLandDamageReasonDamageType actual
    ) {
        assertThat(actual)
            .as("Verify CultivatedLandDamageReasonDamageType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReasonDamageTypeUpdatableFieldsEquals(
        CultivatedLandDamageReasonDamageType expected,
        CultivatedLandDamageReasonDamageType actual
    ) {
        assertThat(actual)
            .as("Verify CultivatedLandDamageReasonDamageType relevant properties")
            .satisfies(a -> assertThat(a.getTypeName()).as("check typeName").isEqualTo(expected.getTypeName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReasonDamageTypeUpdatableRelationshipsEquals(
        CultivatedLandDamageReasonDamageType expected,
        CultivatedLandDamageReasonDamageType actual
    ) {
        // empty method
    }
}
