package lk.geoedge.interoperability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CultivatedLandFarmerLandAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandFarmerLandAllPropertiesEquals(
        CultivatedLandFarmerLand expected,
        CultivatedLandFarmerLand actual
    ) {
        assertCultivatedLandFarmerLandAutoGeneratedPropertiesEquals(expected, actual);
        assertCultivatedLandFarmerLandAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandFarmerLandAllUpdatablePropertiesEquals(
        CultivatedLandFarmerLand expected,
        CultivatedLandFarmerLand actual
    ) {
        assertCultivatedLandFarmerLandUpdatableFieldsEquals(expected, actual);
        assertCultivatedLandFarmerLandUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandFarmerLandAutoGeneratedPropertiesEquals(
        CultivatedLandFarmerLand expected,
        CultivatedLandFarmerLand actual
    ) {
        assertThat(actual)
            .as("Verify CultivatedLandFarmerLand auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandFarmerLandUpdatableFieldsEquals(
        CultivatedLandFarmerLand expected,
        CultivatedLandFarmerLand actual
    ) {
        assertThat(actual)
            .as("Verify CultivatedLandFarmerLand relevant properties")
            .satisfies(a -> assertThat(a.getLandStatus()).as("check landStatus").isEqualTo(expected.getLandStatus()))
            .satisfies(a -> assertThat(a.getUrea()).as("check urea").isEqualTo(expected.getUrea()))
            .satisfies(a -> assertThat(a.getMop()).as("check mop").isEqualTo(expected.getMop()))
            .satisfies(a -> assertThat(a.getTsp()).as("check tsp").isEqualTo(expected.getTsp()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getAddedBy()).as("check addedBy").isEqualTo(expected.getAddedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandFarmerLandUpdatableRelationshipsEquals(
        CultivatedLandFarmerLand expected,
        CultivatedLandFarmerLand actual
    ) {
        // empty method
    }
}
