package lk.geoedge.interoperability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CultivatedLandDamageReportDamageTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReportDamageTypeAllPropertiesEquals(
        CultivatedLandDamageReportDamageType expected,
        CultivatedLandDamageReportDamageType actual
    ) {
        assertCultivatedLandDamageReportDamageTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertCultivatedLandDamageReportDamageTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReportDamageTypeAllUpdatablePropertiesEquals(
        CultivatedLandDamageReportDamageType expected,
        CultivatedLandDamageReportDamageType actual
    ) {
        assertCultivatedLandDamageReportDamageTypeUpdatableFieldsEquals(expected, actual);
        assertCultivatedLandDamageReportDamageTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReportDamageTypeAutoGeneratedPropertiesEquals(
        CultivatedLandDamageReportDamageType expected,
        CultivatedLandDamageReportDamageType actual
    ) {
        assertThat(actual)
            .as("Verify CultivatedLandDamageReportDamageType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReportDamageTypeUpdatableFieldsEquals(
        CultivatedLandDamageReportDamageType expected,
        CultivatedLandDamageReportDamageType actual
    ) {
        assertThat(actual)
            .as("Verify CultivatedLandDamageReportDamageType relevant properties")
            .satisfies(a -> assertThat(a.getTypeName()).as("check typeName").isEqualTo(expected.getTypeName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReportDamageTypeUpdatableRelationshipsEquals(
        CultivatedLandDamageReportDamageType expected,
        CultivatedLandDamageReportDamageType actual
    ) {
        // empty method
    }
}
