package lk.geoedge.interoperability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CultivatedLandDamageReportDamageCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReportDamageCategoryAllPropertiesEquals(
        CultivatedLandDamageReportDamageCategory expected,
        CultivatedLandDamageReportDamageCategory actual
    ) {
        assertCultivatedLandDamageReportDamageCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertCultivatedLandDamageReportDamageCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReportDamageCategoryAllUpdatablePropertiesEquals(
        CultivatedLandDamageReportDamageCategory expected,
        CultivatedLandDamageReportDamageCategory actual
    ) {
        assertCultivatedLandDamageReportDamageCategoryUpdatableFieldsEquals(expected, actual);
        assertCultivatedLandDamageReportDamageCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReportDamageCategoryAutoGeneratedPropertiesEquals(
        CultivatedLandDamageReportDamageCategory expected,
        CultivatedLandDamageReportDamageCategory actual
    ) {
        assertThat(actual)
            .as("Verify CultivatedLandDamageReportDamageCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReportDamageCategoryUpdatableFieldsEquals(
        CultivatedLandDamageReportDamageCategory expected,
        CultivatedLandDamageReportDamageCategory actual
    ) {
        assertThat(actual)
            .as("Verify CultivatedLandDamageReportDamageCategory relevant properties")
            .satisfies(a -> assertThat(a.getCategoryName()).as("check categoryName").isEqualTo(expected.getCategoryName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedLandDamageReportDamageCategoryUpdatableRelationshipsEquals(
        CultivatedLandDamageReportDamageCategory expected,
        CultivatedLandDamageReportDamageCategory actual
    ) {
        // empty method
    }
}
