package lk.geoedge.interoperability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CultivatedCropLandSeasonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedCropLandSeasonAllPropertiesEquals(
        CultivatedCropLandSeason expected,
        CultivatedCropLandSeason actual
    ) {
        assertCultivatedCropLandSeasonAutoGeneratedPropertiesEquals(expected, actual);
        assertCultivatedCropLandSeasonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedCropLandSeasonAllUpdatablePropertiesEquals(
        CultivatedCropLandSeason expected,
        CultivatedCropLandSeason actual
    ) {
        assertCultivatedCropLandSeasonUpdatableFieldsEquals(expected, actual);
        assertCultivatedCropLandSeasonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedCropLandSeasonAutoGeneratedPropertiesEquals(
        CultivatedCropLandSeason expected,
        CultivatedCropLandSeason actual
    ) {
        assertThat(actual)
            .as("Verify CultivatedCropLandSeason auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedCropLandSeasonUpdatableFieldsEquals(
        CultivatedCropLandSeason expected,
        CultivatedCropLandSeason actual
    ) {
        assertThat(actual)
            .as("Verify CultivatedCropLandSeason relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPeriod()).as("check period").isEqualTo(expected.getPeriod()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCultivatedCropLandSeasonUpdatableRelationshipsEquals(
        CultivatedCropLandSeason expected,
        CultivatedCropLandSeason actual
    ) {
        // empty method
    }
}
