package lk.geoedge.interoperability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DamageTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamageTypeAllPropertiesEquals(DamageType expected, DamageType actual) {
        assertDamageTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertDamageTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamageTypeAllUpdatablePropertiesEquals(DamageType expected, DamageType actual) {
        assertDamageTypeUpdatableFieldsEquals(expected, actual);
        assertDamageTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamageTypeAutoGeneratedPropertiesEquals(DamageType expected, DamageType actual) {
        assertThat(actual)
            .as("Verify DamageType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamageTypeUpdatableFieldsEquals(DamageType expected, DamageType actual) {
        assertThat(actual)
            .as("Verify DamageType relevant properties")
            .satisfies(a -> assertThat(a.getTypeName()).as("check typeName").isEqualTo(expected.getTypeName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamageTypeUpdatableRelationshipsEquals(DamageType expected, DamageType actual) {
        // empty method
    }
}
