package lk.geoedge.interoperability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DamagesAllAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesAllAllPropertiesEquals(DamagesAll expected, DamagesAll actual) {
        assertDamagesAllAutoGeneratedPropertiesEquals(expected, actual);
        assertDamagesAllAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesAllAllUpdatablePropertiesEquals(DamagesAll expected, DamagesAll actual) {
        assertDamagesAllUpdatableFieldsEquals(expected, actual);
        assertDamagesAllUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesAllAutoGeneratedPropertiesEquals(DamagesAll expected, DamagesAll actual) {
        assertThat(actual)
            .as("Verify DamagesAll auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesAllUpdatableFieldsEquals(DamagesAll expected, DamagesAll actual) {
        assertThat(actual)
            .as("Verify DamagesAll relevant properties")
            .satisfies(a -> assertThat(a.getDamageName()).as("check damageName").isEqualTo(expected.getDamageName()))
            .satisfies(a -> assertThat(a.getDamageCode()).as("check damageCode").isEqualTo(expected.getDamageCode()))
            .satisfies(a -> assertThat(a.getDamageFamily()).as("check damageFamily").isEqualTo(expected.getDamageFamily()))
            .satisfies(a -> assertThat(a.getDamageGenus()).as("check damageGenus").isEqualTo(expected.getDamageGenus()))
            .satisfies(a -> assertThat(a.getDamageSpecies()).as("check damageSpecies").isEqualTo(expected.getDamageSpecies()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getAddedBy()).as("check addedBy").isEqualTo(expected.getAddedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesAllUpdatableRelationshipsEquals(DamagesAll expected, DamagesAll actual) {
        assertThat(actual)
            .as("Verify DamagesAll relationships")
            .satisfies(a -> assertThat(a.getDamageCategory()).as("check damageCategory").isEqualTo(expected.getDamageCategory()))
            .satisfies(a -> assertThat(a.getDamageType()).as("check damageType").isEqualTo(expected.getDamageType()));
    }
}
