package lk.geoedge.interoperability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DamagesTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesTypeAllPropertiesEquals(DamagesType expected, DamagesType actual) {
        assertDamagesTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertDamagesTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesTypeAllUpdatablePropertiesEquals(DamagesType expected, DamagesType actual) {
        assertDamagesTypeUpdatableFieldsEquals(expected, actual);
        assertDamagesTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesTypeAutoGeneratedPropertiesEquals(DamagesType expected, DamagesType actual) {
        assertThat(actual)
            .as("Verify DamagesType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesTypeUpdatableFieldsEquals(DamagesType expected, DamagesType actual) {
        assertThat(actual)
            .as("Verify DamagesType relevant properties")
            .satisfies(a -> assertThat(a.getTypeName()).as("check typeName").isEqualTo(expected.getTypeName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesTypeUpdatableRelationshipsEquals(DamagesType expected, DamagesType actual) {
        // empty method
    }
}
