package lk.geoedge.interoperability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DamagesCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesCategoryAllPropertiesEquals(DamagesCategory expected, DamagesCategory actual) {
        assertDamagesCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertDamagesCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesCategoryAllUpdatablePropertiesEquals(DamagesCategory expected, DamagesCategory actual) {
        assertDamagesCategoryUpdatableFieldsEquals(expected, actual);
        assertDamagesCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesCategoryAutoGeneratedPropertiesEquals(DamagesCategory expected, DamagesCategory actual) {
        assertThat(actual)
            .as("Verify DamagesCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesCategoryUpdatableFieldsEquals(DamagesCategory expected, DamagesCategory actual) {
        assertThat(actual)
            .as("Verify DamagesCategory relevant properties")
            .satisfies(a -> assertThat(a.getCategoryName()).as("check categoryName").isEqualTo(expected.getCategoryName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamagesCategoryUpdatableRelationshipsEquals(DamagesCategory expected, DamagesCategory actual) {
        // empty method
    }
}
