package lk.geoedge.interoperability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DamageCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamageCategoryAllPropertiesEquals(DamageCategory expected, DamageCategory actual) {
        assertDamageCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertDamageCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamageCategoryAllUpdatablePropertiesEquals(DamageCategory expected, DamageCategory actual) {
        assertDamageCategoryUpdatableFieldsEquals(expected, actual);
        assertDamageCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamageCategoryAutoGeneratedPropertiesEquals(DamageCategory expected, DamageCategory actual) {
        assertThat(actual)
            .as("Verify DamageCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamageCategoryUpdatableFieldsEquals(DamageCategory expected, DamageCategory actual) {
        assertThat(actual)
            .as("Verify DamageCategory relevant properties")
            .satisfies(a -> assertThat(a.getCategoryName()).as("check categoryName").isEqualTo(expected.getCategoryName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDamageCategoryUpdatableRelationshipsEquals(DamageCategory expected, DamageCategory actual) {
        // empty method
    }
}
