package lk.geoedge.interoperability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IndexPayoutEventListSeasonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndexPayoutEventListSeasonAllPropertiesEquals(
        IndexPayoutEventListSeason expected,
        IndexPayoutEventListSeason actual
    ) {
        assertIndexPayoutEventListSeasonAutoGeneratedPropertiesEquals(expected, actual);
        assertIndexPayoutEventListSeasonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndexPayoutEventListSeasonAllUpdatablePropertiesEquals(
        IndexPayoutEventListSeason expected,
        IndexPayoutEventListSeason actual
    ) {
        assertIndexPayoutEventListSeasonUpdatableFieldsEquals(expected, actual);
        assertIndexPayoutEventListSeasonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndexPayoutEventListSeasonAutoGeneratedPropertiesEquals(
        IndexPayoutEventListSeason expected,
        IndexPayoutEventListSeason actual
    ) {
        assertThat(actual)
            .as("Verify IndexPayoutEventListSeason auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndexPayoutEventListSeasonUpdatableFieldsEquals(
        IndexPayoutEventListSeason expected,
        IndexPayoutEventListSeason actual
    ) {
        assertThat(actual)
            .as("Verify IndexPayoutEventListSeason relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPeriod()).as("check period").isEqualTo(expected.getPeriod()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndexPayoutEventListSeasonUpdatableRelationshipsEquals(
        IndexPayoutEventListSeason expected,
        IndexPayoutEventListSeason actual
    ) {
        // empty method
    }
}
