package lk.geoedge.interoperability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InsuranceCultivatedLandFarmerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsuranceCultivatedLandFarmerAllPropertiesEquals(
        InsuranceCultivatedLandFarmer expected,
        InsuranceCultivatedLandFarmer actual
    ) {
        assertInsuranceCultivatedLandFarmerAutoGeneratedPropertiesEquals(expected, actual);
        assertInsuranceCultivatedLandFarmerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsuranceCultivatedLandFarmerAllUpdatablePropertiesEquals(
        InsuranceCultivatedLandFarmer expected,
        InsuranceCultivatedLandFarmer actual
    ) {
        assertInsuranceCultivatedLandFarmerUpdatableFieldsEquals(expected, actual);
        assertInsuranceCultivatedLandFarmerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsuranceCultivatedLandFarmerAutoGeneratedPropertiesEquals(
        InsuranceCultivatedLandFarmer expected,
        InsuranceCultivatedLandFarmer actual
    ) {
        assertThat(actual)
            .as("Verify InsuranceCultivatedLandFarmer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsuranceCultivatedLandFarmerUpdatableFieldsEquals(
        InsuranceCultivatedLandFarmer expected,
        InsuranceCultivatedLandFarmer actual
    ) {
        assertThat(actual)
            .as("Verify InsuranceCultivatedLandFarmer relevant properties")
            .satisfies(a -> assertThat(a.getFarmerId()).as("check farmerId").isEqualTo(expected.getFarmerId()))
            .satisfies(a -> assertThat(a.getFarmerName()).as("check farmerName").isEqualTo(expected.getFarmerName()))
            .satisfies(a -> assertThat(a.getNicNo()).as("check nicNo").isEqualTo(expected.getNicNo()))
            .satisfies(a -> assertThat(a.getAddressFirstLine()).as("check addressFirstLine").isEqualTo(expected.getAddressFirstLine()))
            .satisfies(a -> assertThat(a.getContactNoEmail()).as("check contactNoEmail").isEqualTo(expected.getContactNoEmail()))
            .satisfies(a -> assertThat(a.getProvinceId()).as("check provinceId").isEqualTo(expected.getProvinceId()))
            .satisfies(a -> assertThat(a.getDistrictId()).as("check districtId").isEqualTo(expected.getDistrictId()))
            .satisfies(a -> assertThat(a.getDsId()).as("check dsId").isEqualTo(expected.getDsId()))
            .satisfies(a -> assertThat(a.getGnId()).as("check gnId").isEqualTo(expected.getGnId()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getAddedDate()).as("check addedDate").isEqualTo(expected.getAddedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsuranceCultivatedLandFarmerUpdatableRelationshipsEquals(
        InsuranceCultivatedLandFarmer expected,
        InsuranceCultivatedLandFarmer actual
    ) {
        // empty method
    }
}
